ESP_ROOT=../esp8266
SKETCH = ./domoio_esp2866.ino
VERBOSE=0
UPLOAD_PORT = /dev/tty.SLAB_USBtoUART
BOARD = nodemcuv2
FLASH_DEF = 4M3M
FS_DIR = ./root_fs
UPLOAD_SPEED=230400
include ./makeEspArduino.mk
